name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality-checks:
    name: 代码质量检查
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 代码格式检查
        run: npm run format:check

      - name: ESLint 检查
        run: npm run lint

      - name: TypeScript 类型检查
        run: npm run type-check

      - name: 死代码检测
        run: npm run dead-code
        continue-on-error: true

  build:
    name: 构建测试
    runs-on: ubuntu-latest
    needs: quality-checks

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建项目
        run: npm run build
        env:
          # 使用占位符环境变量以通过构建
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'test-jwt-secret-minimum-32-characters-for-hs256-algorithm-security' }}
          BCRYPT_SALT_ROUNDS: 10

      - name: 检查构建产物
        run: |
          if [ ! -d ".next" ]; then
            echo "构建失败: .next 目录不存在"
            exit 1
          fi
          echo "构建成功"

  dependency-audit:
    name: 依赖安全审计
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 依赖安全审计
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: 检查未使用的依赖
        run: |
          npm install -g depcheck
          depcheck --ignores="@types/*,eslint-config-*,autoprefixer,tailwindcss,eslint,knip,depcheck"
        continue-on-error: true
